**Github Repo:**

https://github.com/AatkaMeraj/Food_waste_management

# Problem Statement

**Food wastage is a significant issue, with many households and restaurants discarding surplus food while numerous people struggle with food insecurity. This project aims to develop a Local Food Wastage Management System, where:**

**Restaurants and individuals can list surplus food.**

**NGOs or individuals in need can claim the food.**

**SQL stores available food details and locations.**

**A Streamlit app enables interaction, filtering, CRUD operation and visualization.**

**BUSINESS USE CASE:**

**Connecting surplus food providers to those in need through a structured platform.**

**Reducing food waste by redistributing excess food efficiently.**

**Enhancing accessibility via geolocation features to locate food easily.**

**Data analysis on food wastage trends for better decision-making.**

In [1]:
import pandas as pd

In [2]:
# loading data

claims= pd.read_csv('/content/drive/MyDrive/claims_data.csv')
providers= pd.read_csv ('/content/drive/MyDrive/providers_data.csv')
receivers= pd.read_csv ('/content/drive/MyDrive/receivers_data.csv')
food_listings= pd.read_csv ('/content/drive/MyDrive/food_listings_data.csv')

#EDA

In [3]:
claims.head()

   Claim_ID  Food_ID  Receiver_ID     Status        Timestamp
0         1      164          908    Pending    3/5/2025 5:26
1         2      353          391  Cancelled  3/11/2025 10:24
2         3      626          492  Completed   3/21/2025 0:59
3         4       61          933  Cancelled    3/4/2025 9:08
4         5      345          229    Pending  3/14/2025 15:17

In [4]:
providers.head()

,Provider_ID,Name,Type,Address,City,Contact
0,1,Gonzales-Cochran,Supermarket,"74347 Christopher Extensions\nAndreamouth, OK ...",New Jessica,+1-600-220-0480
1,2,"Nielsen, Johnson and Fuller",Grocery Store,"91228 Hanson Stream\nWelchtown, OR 27136",East Sheena,+1-925-283-8901x6297
2,3,Miller-Black,Supermarket,"561 Martinez Point Suite 507\nGuzmanchester, W...",Lake Jesusview,001-517-295-2206
3,4,"Clark, Prince and Williams",Grocery Store,"467 Bell Trail Suite 409\nPort Jesus, IA 61188",Mendezmouth,556.944.8935x401
4,5,Coleman-Farley,Grocery Store,"078 Matthew Creek Apt. 319\nSaraborough, MA 53978",Valentineside,193.714.6577

In [5]:
receivers.head()

   Receiver_ID          Name        Type               City           Contact
0            1  Donald Gomez     Shelter     Port Carlburgh     (955)922-5295
1            2  Laurie Ramos  Individual         Lewisburgh      761.042.1570
2            3  Ashley Mckee         NGO  South Randalltown  691-023-0094x856
3            4    Erika Rose         NGO   South Shaneville        8296491111
4            5   John Romero  Individual          Bakerport      067.491.0154

In [6]:
food_listings.head()

,Food_ID,Food_Name,Quantity,Expiry_Date,Provider_ID,Provider_Type,Location,Food_Type,Meal_Type
0,1,Bread,43,2025-03-17,110,Grocery Store,South Kellyville,Non-Vegetarian,Breakfast
1,2,Soup,22,2025-03-24,791,Grocery Store,West James,Non-Vegetarian,Dinner
2,3,Fruits,46,2025-03-28,478,Catering Service,Lake Regina,Vegan,Breakfast
3,4,Fruits,15,2025-03-16,930,Restaurant,Kellytown,Vegan,Lunch
4,5,Soup,14,2025-03-19,279,Restaurant,Garciaport,Vegan,Dinner

In [12]:
claims.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Claim_ID     1000 non-null   int64
 1   Food_ID      1000 non-null   int64
 2   Receiver_ID  1000 non-null   int64
 3   Status       1000 non-null   object
 4   Timestamp    1000 non-null   object
dtypes: int64(3), object(2)
memory usage: 39.2+ KB

In [13]:
providers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Provider_ID  1000 non-null   int64
 1   Name         1000 non-null   object
 2   Type         1000 non-null   object
 3   Address      1000 non-null   object
 4   City         1000 non-null   object
 5   Contact      1000 non-null   object
dtypes: int64(1), object(5)
memory usage: 47.0+ KB

In [14]:
receivers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Receiver_ID  1000 non-null   int64
 1   Name         1000 non-null   object
 2   Type         1000 non-null   object
 3   City         1000 non-null   object
 4   Contact      1000 non-null   object
dtypes: int64(1), object(4)
memory usage: 39.2+ KB

In [15]:
food_listings.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Food_ID        1000 non-null   int64
 1   Food_Name      1000 non-null   object
 2   Quantity       1000 non-null   int64
 3   Expiry_Date    1000 non-null   object
 4   Provider_ID    1000 non-null   int64
 5   Provider_Type  1000 non-null   object
 6   Location       1000 non-null   object
 7   Food_Type      1000 non-null   object
 8   Meal_Type      1000 non-null   object
dtypes: int64(3), object(6)
memory usage: 70.4+ KB

In [7]:
claims.isnull().sum()

Claim_ID       0
Food_ID        0
Receiver_ID    0
Status         0
Timestamp      0
dtype: int64

In [8]:
providers.isnull().sum()

Provider_ID    0
Name           0
Type           0
Address        0
City           0
Contact        0
dtype: int64

In [9]:
receivers.isnull().sum()

Receiver_ID    0
Name           0
Type           0
City           0
Contact        0
dtype: int64

In [11]:
food_listings.isnull().sum()

Food_ID          0
Food_Name        0
Quantity         0
Expiry_Date      0
Provider_ID      0
Provider_Type    0
Location         0
Food_Type        0
Meal_Type        0
dtype: int64

**The tables have no null rows.**

In [24]:
# check for nulls

claims.duplicated().sum()

np.int64(0)

In [21]:
providers.duplicated().sum()

np.int64(0)

In [22]:
receivers.duplicated().sum()

np.int64(0)

In [23]:
food_listings.duplicated().sum()

np.int64(0)

**The data has no duplicate rows.**

In [21]:
# converting timestamp columns to pandas date-time

claims['Timestamp']= pd.to_datetime(claims['Timestamp'])

food_listings['Expiry_Date']= pd.to_datetime(food_listings['Expiry_Date'])

# Visualizations

In [6]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import plotly.express as px

In [3]:
# Merge datasets

df = claims.merge(food_listings, on="Food_ID", how="left") \
                    .merge(providers, on="Provider_ID", how="left", suffixes=("", "_provider")) \
                    .merge(receivers, on="Receiver_ID", how="left", suffixes=("", "_receiver"))

In [4]:
df.head()

,Claim_ID,Food_ID,Receiver_ID,Status,Timestamp,Food_Name,Quantity,Expiry_Date,Provider_ID,Provider_Type,...,Meal_Type,Name,Type,Address,City,Contact,Name_receiver,Type_receiver,City_receiver,Contact_receiver
0,1,164,908,Pending,3/5/2025 5:26,Dairy,22,2025-03-27,432,Restaurant,...,Dinner,Meyer and Sons,Restaurant,08209 Eaton Streets Apt. 968\nSouth Laurenside...,Carolchester,001-738-662-6338,Abigail Crawford,NGO,Lake Shawn,(010)152-8668
1,2,353,391,Cancelled,3/11/2025 10:24,Fruits,5,2025-03-29,418,Restaurant,...,Lunch,"Schwartz, Odonnell and Padilla",Restaurant,"23011 Barnett Falls Apt. 524\nWest Cameron, WY...",Deborahfurt,955-658-8107x92494,Regina Munoz,NGO,Lake Clinton,585.955.3149
2,3,626,492,Completed,3/21/2025 0:59,Salad,37,2025-03-29,274,Supermarket,...,Breakfast,Shields-Moore,Supermarket,"922 Bailey Overpass Suite 885\nNew William, VA...",New Dawnborough,9332911651,Julie Lewis,NGO,South Steven,(557)352-3497x4606
3,4,61,933,Cancelled,3/4/2025 9:08,Fruits,33,2025-03-22,243,Catering Service,...,Lunch,Davis-Hurley,Catering Service,"687 Sparks Forks\nEast Patricia, NC 25546",West Catherine,(172)389-0239x87614,Jodi Lee,NGO,West Paulfort,3517962649
4,5,345,229,Pending,3/14/2025 15:17,Pasta,14,2025-03-20,346,Grocery Store,...,Lunch,"Phillips, Wolfe and Martin",Grocery Store,Unit 1376 Box 6294\nDPO AE 62072,Thomasville,001-548-413-4962,Tina Watkins,Shelter,Bushview,7774795306

In [5]:
df.columns

Index(['Claim_ID', 'Food_ID', 'Receiver_ID', 'Status', 'Timestamp',
       'Food_Name', 'Quantity', 'Expiry_Date', 'Provider_ID', 'Provider_Type',
       'Location', 'Food_Type', 'Meal_Type', 'Name', 'Type', 'Address', 'City',
       'Contact', 'Name_receiver', 'Type_receiver', 'City_receiver',
       'Contact_receiver'],
      dtype='object')

In [38]:
# claim status

fig = px.pie(df, names="Status", width=500,
    height=500, title="Claims Status Distribution")
fig.show()

The distribution of Claims Status is roughly uniform across all the three categories- Completed, Cancelled and Pending.

In [12]:
# Food type distribution

fig5 = px.pie(food_listings, names="Food_Type", width=500, height=500,  title="Food Type Distribution")
fig5.show()

Food Type distribution is also almost equally distributed among its Types like Vegetarian, Vegan and Non-Vegetarian.

In [14]:
# Meal type distribution
fig6 = px.pie(food_listings, names="Meal_Type", height=500, width=500, title="Meal Type Distribution")
fig6.show()

The distribution of meal types is very balanced, with around 25% in each of the 4 categories, indicating that meal preferences are evenly spread, with no single type dominating consumption.

In [59]:
# claim status over time

# Group by date and status

counts = (
    df.groupby([df["Timestamp"].dt.date, "Status"])
    .size()
    .reset_index(name="Count")
)

# Stacked bar chart
fig = px.bar(
    counts,
    x="Timestamp",
    y="Count",
    color="Status",
    title="Claims Over Time by Status",
    width=900,
    height=500
)

fig.show()

The three status categories — Pending, Cancelled, and Completed — are almost in equal proportions, at around 33% each.

Claim stays usually uniform, with peaks around March 12 and March 18, both exceeding 60 total claims.

Pending claims form a large share of the total, while Cancelled claims fluctuate more sharply.

Completed claims remain consistent, showing less variation than other statuses.

In [8]:
# Top providers by number of claims

provider_counts = df['Name'].value_counts().reset_index()
provider_counts.columns = ["Provider_Name", "Count"]
fig = px.bar(provider_counts.head(10), x="Provider_Name", y="Count", title="Top 10 Providers")
fig.show()

Butler-Richardson stands out as the leading provider being way ahead of others.

The next two providers, Rogers-Warren and Nelson LLC are next highest providers, and the remaining providers follow after these.

Overall, there’s a noticeable gap between the top provider and the rest, indicating concentration by one or two providers.

In [9]:
 Top receivers by number of claims

receiver_counts = df['Name_receiver'].value_counts().reset_index()
receiver_counts.columns = ["Receiver_Name", "Count"]
fig4 = px.bar(receiver_counts.head(10), x="Receiver_Name", y="Count", title="Top Receivers by Claims")
fig4.show()

The top receivers like Anthony Garcia, William Frederick, Matthew Webb, and Scott Hunter lead with 5 claims each, showing the highest activity.

Donald Caldwell, Alvin West, Kristina Simpson, and others, follow closely with 4 claims, reflecting a fairly balanced distribution.

Overall, there’s only a slight gap between the top and others, indicating claims are quite evenly spread across receivers.

In [26]:
# Quantity of food claimed over time

df['Timestamp']= pd.to_datetime(df['Timestamp'])

# Group by date
df_daily = (
    df.groupby(df["Timestamp"].dt.date)["Quantity"]
    .sum()
    .reset_index()
)

# Line chart
fig = px.line(
    df_daily,
    x="Timestamp",
    y="Quantity",
    title="Quantity of Food Claimed Over Time"
)
fig.show()

Food claims fluctuate daily, with noticeable spikes around mid-month.

There’s a steady decline after March 18, with the lowest claims observed on March 21, which may indicate reduced supply or less food availability.

The pattern suggests a cyclical demand, where claims rise every few days before dropping, possibly reflecting weekly distribution schedules or donation cycles.

In [5]:
# Expiry date proximity vs claims

df['Expiry_Date']= pd.to_datetime(df['Expiry_Date'])
df['Timestamp']= pd.to_datetime(df['Timestamp'])

df['Days_to_Expiry'] = (df['Expiry_Date'] - df['Timestamp']).dt.days

In [33]:
# quantity claimed by expiry time range

import numpy as np

# Separate expired and non-expired
expired_df = df[df["Days_to_Expiry"] < 0]
non_expired_df = df[df["Days_to_Expiry"] >= 0]

# Create bins
max_days = int(np.ceil(non_expired_df["Days_to_Expiry"].max()))
bins = range(0, max_days + 5, 5)
labels = [f"{bins[i]}-{bins[i+1]} days" for i in range(len(bins)-1)]

non_expired_df["Expiry_Range"] = pd.cut(
    non_expired_df["Days_to_Expiry"],
    bins=bins,
    labels=labels,
    include_lowest=True
)

# Group and sum quantities
non_expired_bins = non_expired_df.groupby("Expiry_Range")["Quantity"].sum().reset_index()

expired_sum = expired_df["Quantity"].sum()
expired_row = pd.DataFrame({"Expiry_Range": ["Expired"], "Quantity": [expired_sum]})

df_bins = pd.concat([expired_row, non_expired_bins], ignore_index=True)

# Plot
fig = px.bar(
    df_bins,
    x="Expiry_Range",
    y="Quantity",
    title="Quantity Claimed by Expiry Time Ranges (Including Expired)",
    text="Quantity"
)
fig.show()

/tmp/ipython-input-2360821153.py:14: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/tmp/ipython-input-2360821153.py:22: FutureWarning:

The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

The highest claimed quantities are for items expiring within 10–15 days (6,314 units), followed closely by 5–10 days and 0–5 days ranges.

Expired items still account for 1,433 units, indicating room for improvement in timely distribution.

Claims drop sharply beyond 15 days to expiry, suggesting lower urgency or demand for longer shelf-life items.